// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVxHbaRS8RUObzkhHsKU2fJSVBwlTWe7Q',
    appId: '1:70899038909:web:ba4e7a74c3ca0ceec095d4',
    messagingSenderId: '70899038909',
    projectId: 'flutterfirebase-e8521',
    authDomain: 'flutterfirebase-e8521.firebaseapp.com',
    storageBucket: 'flutterfirebase-e8521.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCay-Ke2Pyykvw-bmI_wuqqVWhXgUlLg9U',
    appId: '1:70899038909:android:738516ddbc454c49c095d4',
    messagingSenderId: '70899038909',
    projectId: 'flutterfirebase-e8521',
    storageBucket: 'flutterfirebase-e8521.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSGDp1p0FhcaIVl8pIxOEf5m3eAXMdFTg',
    appId: '1:70899038909:ios:39800a58cdb8eb8fc095d4',
    messagingSenderId: '70899038909',
    projectId: 'flutterfirebase-e8521',
    storageBucket: 'flutterfirebase-e8521.appspot.com',
    androidClientId: '70899038909-pbd18kh5u346vbch62p2l56ivtlrd3d6.apps.googleusercontent.com',
    iosClientId: '70899038909-el7ersl3i9almqnoq5h42vur9e7302nr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSGDp1p0FhcaIVl8pIxOEf5m3eAXMdFTg',
    appId: '1:70899038909:ios:ecbdc459e8838dabc095d4',
    messagingSenderId: '70899038909',
    projectId: 'flutterfirebase-e8521',
    storageBucket: 'flutterfirebase-e8521.appspot.com',
    androidClientId: '70899038909-pbd18kh5u346vbch62p2l56ivtlrd3d6.apps.googleusercontent.com',
    iosClientId: '70899038909-93ac3o14vuf2t2mt8tu18udolrhjj2bh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
